### ISSUE TITLE
Copy directly the emoji instead of code.

### ISSUE THREAD

**Issue by mathieutu** [Quilljou/alfred-gitmoji-workflow#1]
Hi.
Thanks for this workflow. Actually the :code: isn't supported anywhere, and especially not in console, or git GUI.

Do you mind copying the emoji character instead?
Thanks.

**Comment by Quilljou** [comment]
OK, I will try

**Comment by Quilljou** [comment]
I released a new version, try it. 
Actually, I don't know the emoji or the code which should be used in the git commit message. The author of gitmoji is using the code for commit message

**Comment by huruji** [comment]
did a good job @Quilljou

**Comment by mathieutu** [comment]
@Quilljou Perfect, thanks ! 👌 
The unicode character is used in gitmoji-cli, and this issue is about that topic: 
https://github.com/carloscuesta/gitmoji/issues/60

For mac, I think it stays the best way.
